// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urccxxutqfkqzcwycqhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyY2N4eHV0cWZrcXpjd3ljcWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTczNTYsImV4cCI6MjA1NjY3MzM1Nn0.TstMF-NCzzrzvgMMmdHh_CyptZpvtlvmvGKAzm0fbuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);